ACTION_SPACE = [
    'rewrite',
    'rewrite -z',
    'refactor',
    'refactor -z',
    'restructure',
    'restructure -z',
    'resub',
    'resub -z',
    'sweep',
    'rr',
    'balance',
    'resyn',
    'resyn2',
    'resyn2a',
    'resyn3',
    'compress',
    'compress2',
    'choice',
    'choice2',
    'rwsat',
    'drwsat2',
    'share',
    'addinit',
    'blif2aig',
    'v2p',
    'g2p',
    '&sw_',
    '&fx_',
    '&dc3',
    '&dc4',
    'src_rw',
    'src_rs',
    'src_rws',
    'resyn2rs',
    'r2rs',
    'compress2rs',
    'c2rs',
    'recadd3'
]