ACTION_SPACE = [
    'rewrite',
    'rewrite -z',
    'refactor',
    'refactor -z',
    # 'restructure',
    # 'restructure -z',
    'resub',
    'resub -z',
    'renode; strash',
    # 'sweep',
    'balance',
    'resyn',
    'resyn2',
    'resyn2a',
    'resyn3',
    'compress',
    'compress2',
    'choice',
    'choice2',
    'rwsat',
    'drwsat2',
    'share',
    # 'addinit',
    # 'blif2aig',
    # '&get; v2p; st; &put',
    # '&get; g2p; st; &put',
    # '&sw_',
    # '&fx_',
    '&get; &dc3; st; &put',
    '&get; &dc4; st; &put',
    'src_rw',
    'src_rs',
    'src_rws',
    'resyn2rs',
    'r2rs',
    'compress2rs',
    'c2rs',
],

DRILL_SPACE = [
    'rewrite',
    'rewrite -z',
    'refactor',
    'refactor -z',
    'resub',
    'resub -z',
    'balance'
]