ACTION_SPACE = [
    '',
    'rewrite',
    'rewrite -z',
    'refactor',
    'refactor -z',
    'resub',
    'resub -z',
    'renode; strash',
    'balance',
    'resyn',
    'resyn2',
    'resyn2a',
    'resyn3',
    'compress',
    'compress2',
    'rwsat',
    'drwsat2',
    'share',
    '&get; &dc3; st; &put',
    '&get; &dc4; st; &put',
    'src_rw',
    'src_rs',
    'src_rws',
    'resyn2rs',
    'r2rs',
    'compress2rs',
    'c2rs',
]

DRILL_SPACE = [
    'rewrite',
    'rewrite -z',
    'refactor',
    'refactor -z',
    'resub',
    'resub -z',
    'balance'
]